completed frontend structure criteria.
learn-academy-2023-alpha/cat-tinder-frontend-beer-tinder-aaron-brandon pull request #1
Opened 2023-04-04 23:40 UTC by BxRay95

2023-04-04 23:43 UTC, sjproctor commented on src/components/Header.js
> +function Header(props) {
This should be `const Header = () => {`

Are you using props?

2023-04-05 18:49 UTC, nmaresrivera11 requested changes
Take a look at the casing inside of your classNames and CSS file

2023-04-05 18:49 UTC, nmaresrivera11 commented on src/App.css
> +.NotFound {
This casing should be kebob not Pascal

2023-04-05 19:00 UTC, nmaresrivera11 approved these changes
NICE

2023-04-05 20:00 UTC, merged